<?php if ($erreur != ''):?>
    <p class="error"><?= $erreur; ?></p>
<?php endif;?>

<form method="post" action="addArticle.php" enctype="multipart/form-data">

<p>
<label for="publishDate">Date de publication</label>
<input type="date" name="publishDate" id="publishDate">
</p>
<p>
<label for="title">Titre de l'article</label>
<input type="text" name="title" id="title">
</p>
<p>
<label for="category"></label>
<select name="category" id="category">Catégories</select>
<?php foreach ($variable as $key => $categorie) {
    # code...
}

<option value=""></option>
</p>
<p>
<label for="content">Message</label>
<input type="textarea" name="content" id="content">
</p>

<p>
<label for="image">Image d'entête</label>
<input type="file" name="image" id="image">
</p>
<p>
<label for="tag">Mots clefs</label>
<input type="textarea" name="tag" id="tag">
</p>
<p>
<label for="statut">Publication</label>
<input type="checkbox" name="statut" id="statut">
</p>
<p>
<input type="submit" value="Enregistrer">
</p>


</form>