    
<?php if ($error):?>
    <p class="error"><?= $error; ?></p>
<?php endif;?>

    <form method="post" action="addUser.php">

        <p>
            <label for="name">Nom</label>
            <input type="text" name="name" id="name" value="<?=$tab['name']?>">
        </p>
        <p>
            <label for="firstName">Prénom</label>
            <input type="text" name="firstName" id="firstName" value="<?=$tab['firstName']?>">
        </p>
        <p>
            <label for="mail">Email</label>
            <input type="mail" name="mail" id="mail" value="<?=$tab['mail']?>"> 
        </p>
        <p>
            <label for="password">Mot de passe</label>
            <input type="password" name="password" id="password" > 
        </p>
        <p>
            <label for="confirm">Confirmation</label>
            <input type="password" name="confirm" id="confirm" > 
        </p>
    
        <p>
            <label for="bio">Bio</label>
            <input type="text" name="bio" id="bio" value="<?=$tab['bio']?>">
        </p>
        <p>
            <label for="avatar">Avatar</label>
           <input type="text" name="avatar" id="avatar" value="<?=$tab['avatar']?>">
        </p>
        <p>
            <label for="userName">Pseudo</label>
           <input type="text" name="userName" id="userName" value="<?=$tab['userName']?>">
        </p>
        <p>
            <label for="role">Rôle</label>
            <select name="role" id="role">
                <option value="admin">Administrateur</option>
                <option value="auteur">Auteur</option>
            </select>
        </p>
        <p>
            <input type="submit" value="Envoyer">
        </p>
    </form>
