    
<?php if ($erreur != ''):?>
    <p class="error"><?= $erreur; ?></p>
<?php endif;?>

    <form method="post" action="addUser.php" enctype="multipart/form-data">

        <p>
            <label for="name">Nom</label>
            <input type="text" name="name" id="name" value="<?=$values['name']?>">
        </p>
        <p>
            <label for="firstName">Prénom</label>
            <input type="text" name="firstName" id="firstName" value="<?=$values['firstName']?>">
        </p>
        <p>
            <label for="mail">Email</label>
            <input type="mail" name="mail" id="mail" value="<?=$values['mail']?>"> 
        </p>
        <p>
            <label for="password">Mot de passe</label>
            <input type="password" name="password" id="password" > 
        </p>
        <p>
            <label for="confirm">Confirmation</label>
            <input type="password" name="confirm" id="confirm" > 
        </p>
    
        <p>
            <label for="bio">Bio</label>
            <input type="text" name="bio" id="bio" value="<?=$values['bio']?>">
        </p>
        <p>
            <label for="avatar">Avatar</label>
           <input type="file" name="avatar" id="avatar" value="<?=$values['avatar']?>">
        </p>
        <p>
            <label for="userName">Pseudo</label>
           <input type="text" name="userName" id="userName" value="<?=$values['userName']?>">
        </p>
        <p>
            <label for="role">Rôle</label>
            <select name="role" id="role">
                <option value="admin">Administrateur</option>
                <option value="auteur">Auteur</option>
            </select>
        </p>
        <p>
            <input type="submit" value="Envoyer">
        </p>
    </form>
